### ISSUE TITLE
Empty list serialization

### ISSUE THREAD

**Issue by colltoaction** [jacebrowning/datafiles#187]
Hi Jace, thanks again for the hard work here! I just had an issue with lists and think there might be a misunderstanding of the YAML spec.

Consider [this test](https://github.com/jacebrowning/datafiles/blob/40c6db10c6a64495f5bdc846a7d7e9067588a138/tests/test_loading.py#L381):

```yaml
items:
-
```

It checks that `items == []`, but that is actually a list with one element. If you run that YAML through any YAML to JSON converter, you'll see the output is:

```json
{
   "items": [
      null
   ]
}
```

In YAML you specify empty lists with:

```yaml
items: []
```

I could try to contribute a fix, but it'll be a breaking change 😞. What do you think?

**Comment by jacebrowning** [comment]
This deviation from the YAML specification was intentional to optimize for the use case of storing YAML files in version control.

By storing `items = []` as:

```
items:
  - 
```

the on-disk list is always bulleted so that adding and removing items is always a one-line change, where adding items to `items: []` will always create a noisier diff and require knowledge of the YAML specification to edit manually.

I'll add clarification here to explain this design decision: https://datafiles.readthedocs.io/en/latest/types/containers/

---

Can expand on the issue you experienced? Maybe I can add a setting to disable this behavior.

**Comment by colltoaction** [comment]
I like the reasoning behind that decision, but the YAML file is not what you want. In fact, take a look at this PR: https://github.com/jacebrowning/datafiles/pull/188. It looks _wronger_ on JSON, but technically it's equivalent to the YAML.

**Comment by jacebrowning** [comment]
I'd also be comfortable removing this behavior for JSON since the version control diff justification does not apply.

Regardless, I'm going to consider adding a [setting](https://datafiles.readthedocs.io/en/latest/settings/) to control the semantic representation of empty lists.

**Comment by jacebrowning** [comment]
@colltoaction when you get a chance, give this version a try: https://pypi.org/project/datafiles/0.11b3/

The new setting is documented here: https://datafiles.readthedocs.io/en/latest/settings/#minimize_list_diffs

**Comment by colltoaction** [comment]
The behavior I see is:

### With `items: List[str] = field(default_factory=list)`

The `items` field is omitted.

### With `items: List[str]`

Still seeing the single-itemed list
